[package]
name = "learn-rust-webapp"
version = "0.1.0"
authors = ["Fabio Gavilondo <fgavilondo@nine.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-session = "0.3.0"
actix-files = "0.2.2"
futures = "0.3.5"
serde = "1.0.115"
serde_json = "1.0.57"
http = "0.2.1"
env_logger = "0.7.1"
chrono = "0.4.15"

